### ISSUE TITLE
大小写是否需要改一下

### ISSUE THREAD

**Issue by larryKra** [zycv/OpenSpeaker#5]
OpenSpeaker/voiceprint/voiceprint_main.cc 
line 89: OpenSpeaker::Features features(sample_rate, feats_dims);

头文件里的定义是
 namespace openspeaker {

大小写不匹配，编译的时候报错了，改成统一的就可以了。

**Comment by zycv** [comment]
Yeah, It's a bug about namespace naming and I've fixed it, thanks for your issue!
